### ISSUE TITLE
RFTools Dialing Device and Botania Mana Tablet

### ISSUE THREAD

**Issue by Xandelan** [BBoldt/Unabridged#318] opened 2015-05-11 01:42 UTC
http://paste.atlauncher.com/view/e4ec01fe

http://paste.atlauncher.com/view/raw/e4ec01fe

If not proper file let me know!

**Comment by BBoldt** [comment] 2015-05-13 22:16
Can't reproduce, it may be fixed in newer version.

**Closed by BBoldt** 2015-05-13 22:16 UTC
