### ISSUE TITLE
Crash related to mossy fence gates

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#234] opened 2015-02-09 17:38 UTC
A village was found which had a graveyard in it. The fence was mossy cobblestone with a wooden fence gate on one side and a mossy cobble fence gate on the other. The server kept ticking the fence gate's collision with a leaf block until the server crashed every 3 minutes or so. 

Anyways, after breaking the mossy cobble fence gate (which was causing the problem), it turned into a wooden fence gate. I couldn't find the mossy fence gate in NEI, but it was rendered perfectly in-world. Makes me wonder if something was in the world, which shouldn't have been? 

You probably can't do anything about it, just thought I'd give a heads-up in case something like this happens to somebody else.

http://pastebin.com/czprxLY4

**Comment by BBoldt** [comment] 2015-02-26 05:45
I'm just going to close this because I can't reproduce it. It will be archived and can be reopened if someone experiences it again.

**Closed by BBoldt** 2015-02-26 05:45 UTC
